import type { AminoAcids, Nutrients } from "./reference";

export type FoodItem = {
  id: string;
  name: string;
  /** per 100 g edible portion */
  nutrients: Nutrients;
  /** mg per g protein */
  amino: AminoAcids;
  category?: string;
  source?: string;
};

const aa = (
  his: number,
  ile: number,
  leu: number,
  lys: number,
  saa: number,
  aaa: number,
  thr: number,
  trp: number,
  val: number,
): AminoAcids => ({ his, ile, leu, lys, saa, aaa, thr, trp, val });

/**
 * Built-in catalog of infant-appropriate foods, used when no external food-API
 * key is configured and as the offline fallback for search.
 * Values are typical composition per 100 g.
 */
export const FOOD_CATALOG: FoodItem[] = [
  {
    id: "local:breast-milk",
    name: "Breast milk, mature",
    nutrients: {
      kcal: 70,
      protein_g: 1.0,
      fat_g: 4.2,
      carb_g: 6.9,
      sugar_g: 6.9,
      sodium_mg: 17,
      iron_mg: 0.03,
      calcium_mg: 32,
      zinc_mg: 0.17,
      vitc_mg: 5,
      vita_ug: 61,
      folate_ug: 5,
      vitd_ug: 0.1,
    },
    amino: aa(25, 56, 105, 68, 42, 100, 47, 17, 63),
  },
  {
    id: "local:infant-formula",
    name: "Infant formula, cow-milk based, prepared",
    nutrients: {
      kcal: 67,
      protein_g: 1.4,
      fat_g: 3.6,
      carb_g: 7.2,
      sugar_g: 7.2,
      sodium_mg: 18,
      iron_mg: 0.8,
      calcium_mg: 51,
      zinc_mg: 0.5,
      vitc_mg: 8,
      vita_ug: 60,
      folate_ug: 10,
      vitd_ug: 1.1,
    },
    amino: aa(27, 52, 100, 80, 38, 96, 47, 14, 60),
  },
  {
    id: "local:oat-porridge",
    name: "Oat porridge, cooked in water",
    nutrients: {
      kcal: 71,
      protein_g: 2.5,
      fat_g: 1.5,
      carb_g: 12,
      fiber_g: 1.7,
      sugar_g: 0.3,
      sodium_mg: 4,
      iron_mg: 0.9,
      calcium_mg: 9,
      zinc_mg: 0.9,
      vitc_mg: 0,
      vita_ug: 0,
      folate_ug: 9,
      vitd_ug: 0,
    },
    amino: aa(22, 38, 74, 42, 45, 89, 33, 13, 53),
  },
  {
    id: "local:rice-cereal",
    name: "Infant rice cereal, prepared",
    nutrients: {
      kcal: 60,
      protein_g: 1.2,
      fat_g: 0.7,
      carb_g: 12,
      fiber_g: 0.4,
      sodium_mg: 5,
      iron_mg: 6.5,
      calcium_mg: 70,
      zinc_mg: 0.6,
      vitc_mg: 6,
      vita_ug: 60,
      folate_ug: 20,
      vitd_ug: 1,
    },
    amino: aa(24, 41, 82, 36, 43, 95, 35, 12, 58),
  },
  {
    id: "local:sweet-potato",
    name: "Sweet potato, boiled, mashed",
    nutrients: {
      kcal: 76,
      protein_g: 1.4,
      fat_g: 0.1,
      carb_g: 17.7,
      fiber_g: 2.5,
      sugar_g: 5.7,
      sodium_mg: 27,
      iron_mg: 0.7,
      calcium_mg: 27,
      zinc_mg: 0.2,
      vitc_mg: 12.8,
      vita_ug: 787,
      folate_ug: 6,
      vitd_ug: 0,
    },
    amino: aa(21, 41, 60, 44, 40, 90, 62, 15, 62),
  },
  {
    id: "local:carrot",
    name: "Carrot, boiled, pureed",
    nutrients: {
      kcal: 35,
      protein_g: 0.8,
      fat_g: 0.2,
      carb_g: 8.2,
      fiber_g: 3,
      sugar_g: 3.5,
      sodium_mg: 58,
      iron_mg: 0.3,
      calcium_mg: 30,
      zinc_mg: 0.2,
      vitc_mg: 3.6,
      vita_ug: 852,
      folate_ug: 14,
      vitd_ug: 0,
    },
    amino: aa(23, 40, 55, 47, 26, 65, 41, 11, 55),
  },
  {
    id: "local:butternut-squash",
    name: "Butternut squash, roasted",
    nutrients: {
      kcal: 40,
      protein_g: 0.9,
      fat_g: 0.1,
      carb_g: 10.5,
      fiber_g: 1.8,
      sugar_g: 2,
      sodium_mg: 4,
      iron_mg: 0.6,
      calcium_mg: 41,
      zinc_mg: 0.1,
      vitc_mg: 15,
      vita_ug: 558,
      folate_ug: 19,
      vitd_ug: 0,
    },
    amino: aa(22, 38, 57, 50, 28, 70, 34, 12, 44),
  },
  {
    id: "local:broccoli",
    name: "Broccoli, steamed",
    nutrients: {
      kcal: 35,
      protein_g: 2.4,
      fat_g: 0.4,
      carb_g: 7.2,
      fiber_g: 3.3,
      sugar_g: 1.4,
      sodium_mg: 41,
      iron_mg: 0.7,
      calcium_mg: 40,
      zinc_mg: 0.5,
      vitc_mg: 65,
      vita_ug: 77,
      folate_ug: 108,
      vitd_ug: 0,
    },
    amino: aa(28, 39, 55, 60, 33, 74, 42, 13, 56),
  },
  {
    id: "local:peas",
    name: "Green peas, boiled",
    nutrients: {
      kcal: 84,
      protein_g: 5.4,
      fat_g: 0.2,
      carb_g: 15.6,
      fiber_g: 5.5,
      sugar_g: 5.9,
      sodium_mg: 3,
      iron_mg: 1.5,
      calcium_mg: 27,
      zinc_mg: 1.2,
      vitc_mg: 14,
      vita_ug: 40,
      folate_ug: 63,
      vitd_ug: 0,
    },
    amino: aa(24, 42, 71, 72, 24, 84, 38, 9, 48),
  },
  {
    id: "local:spinach",
    name: "Spinach, cooked",
    nutrients: {
      kcal: 23,
      protein_g: 3,
      fat_g: 0.3,
      carb_g: 3.8,
      fiber_g: 2.4,
      sodium_mg: 70,
      iron_mg: 3.6,
      calcium_mg: 136,
      zinc_mg: 0.8,
      vitc_mg: 9.8,
      vita_ug: 524,
      folate_ug: 146,
      vitd_ug: 0,
    },
    amino: aa(24, 43, 76, 59, 40, 92, 44, 16, 51),
  },
  {
    id: "local:apple",
    name: "Apple, stewed, unsweetened",
    nutrients: {
      kcal: 53,
      protein_g: 0.2,
      fat_g: 0.1,
      carb_g: 14,
      fiber_g: 1.7,
      sugar_g: 11.6,
      sodium_mg: 2,
      iron_mg: 0.1,
      calcium_mg: 5,
      zinc_mg: 0.04,
      vitc_mg: 2,
      vita_ug: 2,
      folate_ug: 1,
      vitd_ug: 0,
    },
    amino: aa(19, 38, 57, 51, 26, 55, 38, 10, 46),
  },
  {
    id: "local:banana",
    name: "Banana, ripe, mashed",
    nutrients: {
      kcal: 89,
      protein_g: 1.1,
      fat_g: 0.3,
      carb_g: 22.8,
      fiber_g: 2.6,
      sugar_g: 12.2,
      sodium_mg: 1,
      iron_mg: 0.3,
      calcium_mg: 5,
      zinc_mg: 0.2,
      vitc_mg: 8.7,
      vita_ug: 3,
      folate_ug: 20,
      vitd_ug: 0,
    },
    amino: aa(70, 30, 65, 45, 32, 70, 33, 11, 43),
  },
  {
    id: "local:pear",
    name: "Pear, stewed",
    nutrients: {
      kcal: 57,
      protein_g: 0.4,
      fat_g: 0.1,
      carb_g: 15.2,
      fiber_g: 3.1,
      sugar_g: 9.8,
      sodium_mg: 1,
      iron_mg: 0.2,
      calcium_mg: 9,
      zinc_mg: 0.1,
      vitc_mg: 4.3,
      vita_ug: 1,
      folate_ug: 7,
      vitd_ug: 0,
    },
    amino: aa(18, 30, 45, 40, 22, 48, 30, 9, 40),
  },
  {
    id: "local:avocado",
    name: "Avocado, mashed",
    nutrients: {
      kcal: 160,
      protein_g: 2,
      fat_g: 14.7,
      carb_g: 8.5,
      fiber_g: 6.7,
      sugar_g: 0.7,
      sodium_mg: 7,
      iron_mg: 0.6,
      calcium_mg: 12,
      zinc_mg: 0.6,
      vitc_mg: 10,
      vita_ug: 7,
      folate_ug: 81,
      vitd_ug: 0,
    },
    amino: aa(28, 46, 80, 72, 55, 90, 52, 15, 62),
  },
  {
    id: "local:full-fat-yogurt",
    name: "Yogurt, plain, whole milk",
    nutrients: {
      kcal: 61,
      protein_g: 3.5,
      fat_g: 3.3,
      carb_g: 4.7,
      sugar_g: 4.7,
      sodium_mg: 46,
      iron_mg: 0.1,
      calcium_mg: 121,
      zinc_mg: 0.6,
      vitc_mg: 0.5,
      vita_ug: 27,
      folate_ug: 7,
      vitd_ug: 0.1,
    },
    amino: aa(27, 52, 98, 86, 35, 100, 45, 14, 66),
  },
  {
    id: "local:cheddar",
    name: "Cheese, cheddar, grated",
    nutrients: {
      kcal: 403,
      protein_g: 25,
      fat_g: 33,
      carb_g: 1.3,
      sugar_g: 0.5,
      sodium_mg: 621,
      iron_mg: 0.7,
      calcium_mg: 721,
      zinc_mg: 3.1,
      vitc_mg: 0,
      vita_ug: 265,
      folate_ug: 18,
      vitd_ug: 0.6,
    },
    amino: aa(29, 53, 96, 82, 34, 105, 37, 14, 67),
  },
  {
    id: "local:whole-milk",
    name: "Cow milk, whole, 3.5%",
    nutrients: {
      kcal: 61,
      protein_g: 3.2,
      fat_g: 3.3,
      carb_g: 4.8,
      sugar_g: 5.1,
      sodium_mg: 43,
      iron_mg: 0.03,
      calcium_mg: 113,
      zinc_mg: 0.4,
      vitc_mg: 0,
      vita_ug: 46,
      folate_ug: 5,
      vitd_ug: 0.1,
    },
    amino: aa(27, 52, 98, 82, 35, 100, 45, 14, 66),
  },
  {
    id: "local:egg",
    name: "Egg, whole, hard cooked",
    nutrients: {
      kcal: 155,
      protein_g: 12.6,
      fat_g: 10.6,
      carb_g: 1.1,
      sugar_g: 1.1,
      sodium_mg: 124,
      iron_mg: 1.2,
      calcium_mg: 50,
      zinc_mg: 1.1,
      vitc_mg: 0,
      vita_ug: 149,
      folate_ug: 44,
      vitd_ug: 2.2,
    },
    amino: aa(24, 54, 86, 73, 57, 100, 49, 15, 68),
  },
  {
    id: "local:chicken",
    name: "Chicken breast, cooked, minced",
    nutrients: {
      kcal: 165,
      protein_g: 31,
      fat_g: 3.6,
      carb_g: 0,
      sodium_mg: 74,
      iron_mg: 1,
      calcium_mg: 15,
      zinc_mg: 1,
      vitc_mg: 0,
      vita_ug: 6,
      folate_ug: 4,
      vitd_ug: 0.1,
    },
    amino: aa(31, 53, 75, 88, 42, 79, 43, 12, 51),
  },
  {
    id: "local:beef",
    name: "Beef, lean, cooked, minced",
    nutrients: {
      kcal: 217,
      protein_g: 26,
      fat_g: 12,
      carb_g: 0,
      sodium_mg: 66,
      iron_mg: 2.6,
      calcium_mg: 18,
      zinc_mg: 6.3,
      vitc_mg: 0,
      vita_ug: 0,
      folate_ug: 8,
      vitd_ug: 0.1,
    },
    amino: aa(33, 46, 81, 86, 39, 78, 45, 11, 51),
  },
  {
    id: "local:salmon",
    name: "Salmon, cooked, flaked",
    nutrients: {
      kcal: 206,
      protein_g: 22,
      fat_g: 12,
      carb_g: 0,
      sodium_mg: 61,
      iron_mg: 0.3,
      calcium_mg: 15,
      zinc_mg: 0.4,
      vitc_mg: 0,
      vita_ug: 12,
      folate_ug: 26,
      vitd_ug: 13.1,
    },
    amino: aa(29, 46, 81, 92, 40, 78, 44, 11, 52),
  },
  {
    id: "local:cod",
    name: "Cod, cooked, flaked",
    nutrients: {
      kcal: 105,
      protein_g: 23,
      fat_g: 0.9,
      carb_g: 0,
      sodium_mg: 78,
      iron_mg: 0.5,
      calcium_mg: 14,
      zinc_mg: 0.5,
      vitc_mg: 1,
      vita_ug: 12,
      folate_ug: 8,
      vitd_ug: 1.2,
    },
    amino: aa(29, 46, 81, 92, 40, 78, 44, 11, 52),
  },
  {
    id: "local:red-lentils",
    name: "Red lentils, cooked",
    nutrients: {
      kcal: 116,
      protein_g: 9,
      fat_g: 0.4,
      carb_g: 20,
      fiber_g: 7.9,
      sugar_g: 1.8,
      sodium_mg: 2,
      iron_mg: 3.3,
      calcium_mg: 19,
      zinc_mg: 1.3,
      vitc_mg: 1.5,
      vita_ug: 0,
      folate_ug: 181,
      vitd_ug: 0,
    },
    amino: aa(28, 43, 72, 70, 22, 88, 36, 9, 50),
  },
  {
    id: "local:chickpeas",
    name: "Chickpeas, cooked, mashed",
    nutrients: {
      kcal: 164,
      protein_g: 8.9,
      fat_g: 2.6,
      carb_g: 27.4,
      fiber_g: 7.6,
      sugar_g: 4.8,
      sodium_mg: 7,
      iron_mg: 2.9,
      calcium_mg: 49,
      zinc_mg: 1.5,
      vitc_mg: 1.3,
      vita_ug: 1,
      folate_ug: 172,
      vitd_ug: 0,
    },
    amino: aa(27, 43, 71, 67, 25, 87, 37, 10, 42),
  },
  {
    id: "local:tofu",
    name: "Tofu, firm",
    nutrients: {
      kcal: 144,
      protein_g: 17,
      fat_g: 8.7,
      carb_g: 2.8,
      fiber_g: 2.3,
      sodium_mg: 14,
      iron_mg: 2.7,
      calcium_mg: 350,
      zinc_mg: 1.6,
      vitc_mg: 0.2,
      vita_ug: 0,
      folate_ug: 19,
      vitd_ug: 0,
    },
    amino: aa(26, 46, 78, 63, 26, 89, 39, 13, 47),
  },
  {
    id: "local:peanut-butter",
    name: "Peanut butter, smooth",
    nutrients: {
      kcal: 588,
      protein_g: 25,
      fat_g: 50,
      carb_g: 20,
      fiber_g: 6,
      sugar_g: 9,
      sodium_mg: 17,
      iron_mg: 1.9,
      calcium_mg: 43,
      zinc_mg: 2.9,
      vitc_mg: 0,
      vita_ug: 0,
      folate_ug: 87,
      vitd_ug: 0,
    },
    amino: aa(26, 34, 65, 36, 25, 100, 33, 10, 42),
  },
  {
    id: "local:tahini",
    name: "Tahini, sesame paste",
    nutrients: {
      kcal: 595,
      protein_g: 17,
      fat_g: 53.8,
      carb_g: 21.2,
      fiber_g: 9.3,
      sugar_g: 0.5,
      sodium_mg: 115,
      iron_mg: 8.9,
      calcium_mg: 426,
      zinc_mg: 4.6,
      vitc_mg: 0,
      vita_ug: 1,
      folate_ug: 98,
      vitd_ug: 0,
    },
    amino: aa(27, 39, 68, 28, 55, 87, 37, 15, 48),
  },
  {
    id: "local:quinoa",
    name: "Quinoa, cooked",
    nutrients: {
      kcal: 120,
      protein_g: 4.4,
      fat_g: 1.9,
      carb_g: 21.3,
      fiber_g: 2.8,
      sugar_g: 0.9,
      sodium_mg: 7,
      iron_mg: 1.5,
      calcium_mg: 17,
      zinc_mg: 1.1,
      vitc_mg: 0,
      vita_ug: 0,
      folate_ug: 42,
      vitd_ug: 0,
    },
    amino: aa(29, 36, 61, 55, 42, 74, 34, 11, 42),
  },
  {
    id: "local:olive-oil",
    name: "Olive oil, extra virgin",
    nutrients: {
      kcal: 884,
      protein_g: 0,
      fat_g: 100,
      carb_g: 0,
      sodium_mg: 2,
      iron_mg: 0.6,
      calcium_mg: 1,
      zinc_mg: 0,
      vitc_mg: 0,
      vita_ug: 0,
      folate_ug: 0,
      vitd_ug: 0,
    },
    amino: aa(0, 0, 0, 0, 0, 0, 0, 0, 0),
  },
  {
    id: "local:unsalted-butter",
    name: "Butter, unsalted",
    nutrients: {
      kcal: 717,
      protein_g: 0.9,
      fat_g: 81,
      carb_g: 0.1,
      sodium_mg: 11,
      iron_mg: 0,
      calcium_mg: 24,
      zinc_mg: 0.1,
      vitc_mg: 0,
      vita_ug: 684,
      folate_ug: 3,
      vitd_ug: 1.5,
    },
    amino: aa(27, 52, 98, 82, 35, 100, 45, 14, 66),
  },
  {
    id: "local:honey",
    name: "Honey",
    nutrients: {
      kcal: 304,
      protein_g: 0.3,
      fat_g: 0,
      carb_g: 82.4,
      sugar_g: 82.1,
      sodium_mg: 4,
      iron_mg: 0.4,
      calcium_mg: 6,
      zinc_mg: 0.2,
      vitc_mg: 0.5,
      vita_ug: 0,
      folate_ug: 2,
      vitd_ug: 0,
    },
    amino: aa(0, 0, 0, 0, 0, 0, 0, 0, 0),
  },
  {
    id: "local:salt",
    name: "Salt, table",
    nutrients: {
      kcal: 0,
      protein_g: 0,
      fat_g: 0,
      carb_g: 0,
      sodium_mg: 38758,
      iron_mg: 0.3,
      calcium_mg: 24,
      zinc_mg: 0.1,
      vitc_mg: 0,
      vita_ug: 0,
      folate_ug: 0,
      vitd_ug: 0,
    },
    amino: aa(0, 0, 0, 0, 0, 0, 0, 0, 0),
  },
];

export function searchCatalog(query: string, limit = 25): FoodItem[] {
  const q = query.trim().toLowerCase();
  if (!q) return FOOD_CATALOG.slice(0, limit);
  return FOOD_CATALOG.filter((f) => f.name.toLowerCase().includes(q)).slice(0, limit);
}
