/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ApproveRecoveryRouteImport } from './routes/approve-recovery'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedBuilderRouteImport } from './routes/_authenticated/builder'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMasterRouteImport } from './routes/_authenticated/master'
import { Route as AuthenticatedPinnedAssetsRouteImport } from './routes/_authenticated/pinned-assets'
import { Route as AuthenticatedRdaRouteImport } from './routes/_authenticated/rda'
import { Route as AuthenticatedAdminActivityRouteImport } from './routes/_authenticated/admin.activity'
import { Route as AuthenticatedMasterIdRouteImport } from './routes/_authenticated/master_.$id'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects.index'
import { Route as AuthenticatedProjectsIdRouteImport } from './routes/_authenticated/projects.$id'
import { Route as AuthenticatedRecipesIndexRouteImport } from './routes/_authenticated/recipes.index'
import { Route as AuthenticatedRecipesIdRouteImport } from './routes/_authenticated/recipes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproveRecoveryRoute = ApproveRecoveryRouteImport.update({
  id: '/approve-recovery',
  path: '/approve-recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBuilderRoute = AuthenticatedBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMasterRoute = AuthenticatedMasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPinnedAssetsRoute =
  AuthenticatedPinnedAssetsRouteImport.update({
    id: '/pinned-assets',
    path: '/pinned-assets',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRdaRoute = AuthenticatedRdaRouteImport.update({
  id: '/rda',
  path: '/rda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminActivityRoute =
  AuthenticatedAdminActivityRouteImport.update({
    id: '/admin/activity',
    path: '/admin/activity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMasterIdRoute = AuthenticatedMasterIdRouteImport.update({
  id: '/master_/$id',
  path: '/master/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIdRoute = AuthenticatedProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecipesIndexRoute =
  AuthenticatedRecipesIndexRouteImport.update({
    id: '/recipes/',
    path: '/recipes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecipesIdRoute = AuthenticatedRecipesIdRouteImport.update({
  id: '/recipes/$id',
  path: '/recipes/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approve-recovery': typeof ApproveRecoveryRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/builder': typeof AuthenticatedBuilderRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/master': typeof AuthenticatedMasterRoute
  '/pinned-assets': typeof AuthenticatedPinnedAssetsRoute
  '/rda': typeof AuthenticatedRdaRoute
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/master/$id': typeof AuthenticatedMasterIdRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/recipes/$id': typeof AuthenticatedRecipesIdRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/recipes/': typeof AuthenticatedRecipesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approve-recovery': typeof ApproveRecoveryRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/builder': typeof AuthenticatedBuilderRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/master': typeof AuthenticatedMasterRoute
  '/pinned-assets': typeof AuthenticatedPinnedAssetsRoute
  '/rda': typeof AuthenticatedRdaRoute
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/master/$id': typeof AuthenticatedMasterIdRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/recipes/$id': typeof AuthenticatedRecipesIdRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/recipes': typeof AuthenticatedRecipesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/approve-recovery': typeof ApproveRecoveryRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/builder': typeof AuthenticatedBuilderRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/master': typeof AuthenticatedMasterRoute
  '/_authenticated/pinned-assets': typeof AuthenticatedPinnedAssetsRoute
  '/_authenticated/rda': typeof AuthenticatedRdaRoute
  '/_authenticated/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/_authenticated/master_/$id': typeof AuthenticatedMasterIdRoute
  '/_authenticated/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/_authenticated/recipes/$id': typeof AuthenticatedRecipesIdRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/recipes/': typeof AuthenticatedRecipesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approve-recovery'
    | '/auth'
    | '/reset-password'
    | '/builder'
    | '/dashboard'
    | '/master'
    | '/pinned-assets'
    | '/rda'
    | '/admin/activity'
    | '/master/$id'
    | '/projects/$id'
    | '/recipes/$id'
    | '/projects/'
    | '/recipes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approve-recovery'
    | '/auth'
    | '/reset-password'
    | '/builder'
    | '/dashboard'
    | '/master'
    | '/pinned-assets'
    | '/rda'
    | '/admin/activity'
    | '/master/$id'
    | '/projects/$id'
    | '/recipes/$id'
    | '/projects'
    | '/recipes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/approve-recovery'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/builder'
    | '/_authenticated/dashboard'
    | '/_authenticated/master'
    | '/_authenticated/pinned-assets'
    | '/_authenticated/rda'
    | '/_authenticated/admin/activity'
    | '/_authenticated/master_/$id'
    | '/_authenticated/projects/$id'
    | '/_authenticated/recipes/$id'
    | '/_authenticated/projects/'
    | '/_authenticated/recipes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ApproveRecoveryRoute: typeof ApproveRecoveryRoute
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approve-recovery': {
      id: '/approve-recovery'
      path: '/approve-recovery'
      fullPath: '/approve-recovery'
      preLoaderRoute: typeof ApproveRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/builder': {
      id: '/_authenticated/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof AuthenticatedBuilderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master': {
      id: '/_authenticated/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof AuthenticatedMasterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pinned-assets': {
      id: '/_authenticated/pinned-assets'
      path: '/pinned-assets'
      fullPath: '/pinned-assets'
      preLoaderRoute: typeof AuthenticatedPinnedAssetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rda': {
      id: '/_authenticated/rda'
      path: '/rda'
      fullPath: '/rda'
      preLoaderRoute: typeof AuthenticatedRdaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/activity': {
      id: '/_authenticated/admin/activity'
      path: '/admin/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AuthenticatedAdminActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master_/$id': {
      id: '/_authenticated/master_/$id'
      path: '/master/$id'
      fullPath: '/master/$id'
      preLoaderRoute: typeof AuthenticatedMasterIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$id': {
      id: '/_authenticated/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthenticatedProjectsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recipes/': {
      id: '/_authenticated/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof AuthenticatedRecipesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recipes/$id': {
      id: '/_authenticated/recipes/$id'
      path: '/recipes/$id'
      fullPath: '/recipes/$id'
      preLoaderRoute: typeof AuthenticatedRecipesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBuilderRoute: typeof AuthenticatedBuilderRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMasterRoute: typeof AuthenticatedMasterRoute
  AuthenticatedPinnedAssetsRoute: typeof AuthenticatedPinnedAssetsRoute
  AuthenticatedRdaRoute: typeof AuthenticatedRdaRoute
  AuthenticatedAdminActivityRoute: typeof AuthenticatedAdminActivityRoute
  AuthenticatedMasterIdRoute: typeof AuthenticatedMasterIdRoute
  AuthenticatedProjectsIdRoute: typeof AuthenticatedProjectsIdRoute
  AuthenticatedRecipesIdRoute: typeof AuthenticatedRecipesIdRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedRecipesIndexRoute: typeof AuthenticatedRecipesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBuilderRoute: AuthenticatedBuilderRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMasterRoute: AuthenticatedMasterRoute,
  AuthenticatedPinnedAssetsRoute: AuthenticatedPinnedAssetsRoute,
  AuthenticatedRdaRoute: AuthenticatedRdaRoute,
  AuthenticatedAdminActivityRoute: AuthenticatedAdminActivityRoute,
  AuthenticatedMasterIdRoute: AuthenticatedMasterIdRoute,
  AuthenticatedProjectsIdRoute: AuthenticatedProjectsIdRoute,
  AuthenticatedRecipesIdRoute: AuthenticatedRecipesIdRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedRecipesIndexRoute: AuthenticatedRecipesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ApproveRecoveryRoute: ApproveRecoveryRoute,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
